### ISSUE TITLE
Mappoints export

### ISSUE THREAD

**Issue by makolele12** [AlejandroSilvestri/osmap#17]
Hi,

I would like to export the generated map points by ORB-SLAM2 but in a readable format (e.g XML or YAML).

I installed the add-on and got it running, however, I just found out that the map points are being saved in binary format in the file "myFirstMap.mappoints".

I am trying to import the 3D coordinates from the points with another program. Is there a way with this add-on to save the mappoints in a readable text format which I could later on parse?

Regards

**Comment by AlejandroSilvestri** [comment]
Hi @makolele12,

Maps are huge.  Writing them in XML would quickly scale to Gigabytes.  That's why this project write maps in binary format, and there is no intention to add text capabilities.

You can open the files and get 3d coordinates with an osmap reader.  [Osmap Viewer](https://github.com/AlejandroSilvestri/Osmap-viewer) is a reader for point cloud visualization, you can easily change the code to get the coordinates or even write them in xml.

**Comment by makolele12** [comment]
Hi @AlejandroSilvestri,

Thanks a lot for your reply. Your input is really useful. I am taking a look to Osmap Viewer.
